#!/bin/sh

# Dumb clipboard manager for tty

usage() { printf "USAGE: ${0##*/} -p[rint]|-d[elete]|-o[ut]|-h[elp]\\nSee README for more info\\n"; exit 1; }

[ "$1" = "-h" ] || [ "$1" = "--help" ] && usage
mkdir -p "$HOME/.cache"  # Create cache directory if it doesn't exist
while getopts ':pdo' args; do case $args in
		p) cat "$HOME/.cache/clipboard"; exit ;;  # Print clipboard
		d) :> "$HOME/.cache/clipboard"; exit ;;   # Delete clipboard
		o) stdout="1" ;;                          # Print stdin to stdout
		?) printf "${0##*/}: invalid option -- $OPTARG\\n" ; exit 1 ;; esac; done
cat > "$HOME/.cache/clipboard"
[ -z "$stdout" ] || cat "$HOME/.cache/clipboard"
